#!/bin/bash
NEW_VALUE=$1
OLD_VALUE="$(($(cat /sys/class/backlight/intel_backlight/brightness) / 13))"

if [[ $1 == "+" ]];
then
	NEW_VALUE=$(($OLD_VALUE + 1))
fi

if [[ $1 == "-" ]];
then
	NEW_VALUE=$(($OLD_VALUE - 1))
fi

if [[ $NEW_VALUE -lt 1 ]];
then
	NEW_VALUE=1
fi

if [[ $NEW_VALUE -gt 100 ]];
then
	NEW_VALUE=100
fi

echo "$(($NEW_VALUE * 13))" > /sys/class/backlight/intel_backlight/brightness
