#!/usr/bin/env bash

choice=`find /etc/netctl -maxdepth 1 -type f -printf "%f\n" | rofi -dmenu`;
if [ -n "$choice" ]; then
    	ok=false
	sudo netctl switch-to $choice && ok=true
   	
	if $ok; then
		notify-send -u normal -a rofi-netctl "Successfully connected to $choice"
	else
		notify-send -u critical -a rofi-netctl "Error connecting to $choice"
	fi
fi
