#!/bin/bash
if [[ $1 == "on" ]];
then
    xrandr --output DP2 --auto --above eDP1
    xrandr --output HDMI1 --auto --right-of DP2
   
    xinput set-prop 14 299 0

    scale-normal
fi

if [[ $1 == "off" ]];
then
    xrandr --output HDMI1 --off
    xrandr --output DP2 --off

    scale-hidpi
fi
