#!/bin/bash

function error
{
    echo "illegal use!"
    echo ""
    echo "use either"
    echo "  webcam on"
    echo "or"
    echo "  webcam off"
    exit
}

if [ "$#" -ne 1 ]; then
    error
fi
	
if [ "$1" = "on" ]; then
    modprobe facetimehd
elif [ "$1" = "off" ]; then
    modprobe -r facetimehd
else
    error
fi
